# Sensors => tone configuration.

# These notes come from this scale:
# https://sevish.com/scaleworkshop/?n=5%20equal%20divisions%20of%202%2F1&l=1B5_2B5_3B5_4B5_5B5&c=~-~-~&w=4&y=46&version=2.5.7.
[[sensors]]
sensor_name = "input_1001"
main_tone = 440.00
[[sensors]]
sensor_name = "input_1002"
main_tone = 505.427
[[sensors]]
sensor_name = "input_1003"
main_tone = 580.583
[[sensors]]
sensor_name = "input_1004"
main_tone = 666.915
[[sensors]]
sensor_name = "input_1005"
main_tone = 766.084


# The notes are a Dmaj6maj7 chord.
# [[sensors]]
# sensor_name = "input_1001"
# main_tone = 293.66
# [[sensors]]
# sensor_name = "input_1002"
# main_tone = 369.99
# [[sensors]]
# sensor_name = "input_1003"
# main_tone = 440.00
# [[sensors]]
# sensor_name = "input_1004"
# main_tone = 493.88
# [[sensors]]
# sensor_name = "input_1005"
# main_tone = 554.37