[[sensors]] # sensor 1
sensor_name = "input_1000"
main_tone = 220.795
[[sensors]] # sensor 2
sensor_name = "input_1001"
main_tone = 582.681 # 218.506 (*2)
[[sensors]] # sensor 3
sensor_name = "input_1002"
main_tone = 384.427
[[sensors]] # sensor 4
sensor_name = "input_1003"
main_tone = 253.627
[[sensors]] # sensor 5
sensor_name = "input_1004"
main_tone = 96.107 # 144.160 (/2)
[[sensors]] # sensor 6
sensor_name = "input_1005"
main_tone = 167.332 # 250.997 (/2)
[[sensors]] # sensor 7
sensor_name = "input_1006"
main_tone = 291.341
[[sensors]] # sensor 8
sensor_name = "input_1007"
main_tone = 441.591 # Double of tone (2).
