# Sensors => tone configuration.

[[sensors]]
sensor_name = "input_1001"
main_tone = 261.63
[[sensors]]
sensor_name = "input_1002"
main_tone = 329.63
[[sensors]]
sensor_name = "input_1003"
main_tone = 392.00